### ISSUE TITLE
Heirloom throws exception when using IAM roles with not enough privileges 

### ISSUE THREAD

**Issue by Gusymochis** [intuit/heirloom#159]
when heirloom tries to retrieve a databag with not enough privileges (using IAM roles authentication) it throws an exception and unparsed XML:

```
/opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/excon-0.25.3/lib/excon/middlewares/expects.rb:10:in `response_call': Expected(200) <=> Actual(403 Forbidden) (Excon::Errors::Forbidden)
  response => #<Excon::Response:0x00000002dcd690 @data={:body=>"<?xml version=\"1.0\"?>\n<Response><Errors><Error><Code>AuthorizationFailure</Code><Message>User (arn:aws:sts::01234567890:assumed-role/cfn-stack-InstancesIamRole-ABCDEFGHI/i-00c000000) does not have permission to perform (sdb:ListDomains) on resource (arn:aws:sdb:us-west-1:01234567890:domain/). Contact account owner.</Message><BoxUsage>0.0000071759</BoxUsage></Error></Errors><RequestID>00000-1234-5678-9012-00abcde1233456</RequestID></Response>", :headers=>{"Transfer-Encoding"=>"chunked", "Date"=>"Thu, 05 Dec 2013 22:25:45 GMT", "Server"=>"Amazon SimpleDB"}, :status=>403, :remote_ip=>"10.xxx.xxx.xxx"}, @body="<?xml version=\"1.0\"?>\n<Response><Errors><Error><Code>AuthorizationFailure</Code><Message>User (arn:aws:sts::01234567890:assumed-role/cfn-stack-InstancesIamRole-ABCDEFGHI/i-00c000000) does not have permission to perform (sdb:ListDomains) on resource (arn:aws:sdb:us-west-1:01234567890:domain/). Contact account owner.</Message><BoxUsage>0.0000071759</BoxUsage></Error></Errors><RequestID>00000-1234-5678-9012-00abcde1233456</RequestID></Response>", @headers={"Transfer-Encoding"=>"chunked", "Date"=>"Thu, 05 Dec 2013 22:25:45 GMT", "Server"=>"Amazon SimpleDB"}, @status=403, @remote_ip="10.xxx.xxx.xxx">
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/excon-0.25.3/lib/excon/middlewares/response_parser.rb:8:in `response_call'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/excon-0.25.3/lib/excon/connection.rb:349:in `response'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/excon-0.25.3/lib/excon/connection.rb:247:in `request'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/excon-0.25.3/lib/excon/middlewares/idempotent.rb:12:in `error_call'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/excon-0.25.3/lib/excon/middlewares/base.rb:10:in `error_call'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/excon-0.25.3/lib/excon/middlewares/base.rb:10:in `error_call'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/excon-0.25.3/lib/excon/connection.rb:260:in `rescue in request'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/excon-0.25.3/lib/excon/connection.rb:220:in `request'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/excon-0.25.3/lib/excon/middlewares/idempotent.rb:12:in `error_call'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/excon-0.25.3/lib/excon/middlewares/base.rb:10:in `error_call'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/excon-0.25.3/lib/excon/middlewares/base.rb:10:in `error_call'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/excon-0.25.3/lib/excon/connection.rb:260:in `rescue in request'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/excon-0.25.3/lib/excon/connection.rb:220:in `request'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/excon-0.25.3/lib/excon/middlewares/idempotent.rb:12:in `error_call'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/excon-0.25.3/lib/excon/middlewares/base.rb:10:in `error_call'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/excon-0.25.3/lib/excon/middlewares/base.rb:10:in `error_call'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/excon-0.25.3/lib/excon/connection.rb:260:in `rescue in request'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/excon-0.25.3/lib/excon/connection.rb:220:in `request'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/fog-1.15.0/lib/fog/xml/sax_parser_connection.rb:36:in `request'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/fog-1.15.0/lib/fog/core/deprecated/connection.rb:18:in `request'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/fog-1.15.0/lib/fog/aws/simpledb.rb:181:in `request'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/fog-1.15.0/lib/fog/aws/requests/simpledb/list_domains.rb:28:in `list_domains'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/heirloom-0.12.1/lib/heirloom/aws/simpledb.rb:23:in `domains'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/heirloom-0.12.1/lib/heirloom/aws/simpledb.rb:27:in `domain_exists?'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/heirloom-0.12.1/lib/heirloom/archive/reader.rb:102:in `domain_exists?'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/heirloom-0.12.1/lib/heirloom/archive/reader.rb:14:in `exists?'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/heirloom-0.12.1/lib/heirloom/archive.rb:63:in `exists?'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/heirloom-0.12.1/lib/heirloom/cli/shared.rb:150:in `ensure_archive_exists'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/heirloom-0.12.1/lib/heirloom/cli/download.rb:34:in `initialize'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/heirloom-0.12.1/lib/heirloom/cli.rb:36:in `new'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/heirloom-0.12.1/lib/heirloom/cli.rb:36:in `start'
    from /opt/intu/heirloom/embedded/lib/ruby/gems/1.9.1/gems/heirloom-0.12.1/bin/heirloom:6:in `<top (required)>'
    from /usr/bin/heirloom:23:in `load'
    from /usr/bin/heirloom:23:in `<main>'
```

**Comment by Gusymochis** [comment]
Stale
